name: Refresh OpenAlex data

on:
  schedule:
    - cron: '5 0 * * *'  # daily 00:05 UTC
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Build JSON
        env:
          OPENALEX_MAILTO: ${{ secrets.OPENALEX_MAILTO || 'arber.hoti@uni-pr.edu' }}
        run: |
          python scripts/build.py
      - name: Commit & push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add site/data/authors.json
          git diff --quiet && echo "No changes" || git commit -m "chore: refresh data"
          git push
